name: bawabba
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  printing: ^5.11.0
  intl: ^0.19.0
  desktop_window: ^0.4.2
  window_manager: ^0.4.3
  flutter_svg: ^2.0.14
  easy_sidemenu: ^0.6.0
  flutter:
    sdk: flutter
  http: ^1.0.0
  flutter_localizations: 
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/Cairo-Regular.ttf
  uses-material-design: true
  

